### ISSUE TITLE
i get this error : NoMethodError - undefined method `settings' for API:Class:

### ISSUE THREAD

**Issue by 85636682** [ruby-grape/grape-swagger#158]
my gem file:

```
# Grape APIs
gem 'grape', github: 'intridea/grape'
gem 'grape-entity'
gem 'grape-swagger'  '0.7.2'
gem 'grape-swagger-rails',  '0.0.10'
```

```
NoMethodError - undefined method `settings' for API:Class:
  grape-swagger (0.7.2) lib/grape-swagger.rb:220:in `content_types_for'
  grape-swagger (0.7.2) lib/grape-swagger.rb:107:in `block in setup'
   () Users/stephen/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/grape-4288dd351938/lib/grape/endpoint.rb:47:in `block in generate_api_method'
   () Users/stephen/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/grape-4288dd351938/lib/grape/endpoint.rb:243:in `run'
   () Users/stephen/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/grape-4288dd351938/lib/grape/endpoint.rb:191:in `block in call!'
   () Users/stephen/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/grape-4288dd351938/lib/grape/middleware/base.rb:24:in `call!'
   () Users/stephen/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/grape-4288dd351938/lib/grape/middleware/base.rb:18:in `call'
   () Users/stephen/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/grape-4288dd351938/lib/grape/middleware/error.rb:27:in `block in call!'
   () Users/stephen/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/grape-4288dd351938/lib/grape/middleware/error.rb:26:in `call!'
   () Users/stephen/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/grape-4288dd351938/lib/grape/middleware/base.rb:18:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  rack (1.5.2) lib/rack/builder.rb:138:in `call'
   () Users/stephen/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/grape-4288dd351938/lib/grape/endpoint.rb:192:in `call!'
   () Users/stephen/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/grape-4288dd351938/lib/grape/endpoint.rb:180:in `call'
  rack-mount (0.8.3) lib/rack/mount/route_set.rb:152:in `block in call'
  rack-mount (0.8.3) lib/rack/mount/code_generation.rb:96:in `block in recognize'
  rack-mount (0.8.3) lib/rack/mount/code_generation.rb:68:in `optimized_each'
  rack-mount (0.8.3) lib/rack/mount/code_generation.rb:95:in `recognize'
  rack-mount (0.8.3) lib/rack/mount/route_set.rb:141:in `call'
   () Users/stephen/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/grape-4288dd351938/lib/grape/api.rb:104:in `call'
   () Users/stephen/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/grape-4288dd351938/lib/grape/api.rb:33:in `call!'
   () Users/stephen/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/grape-4288dd351938/lib/grape/api.rb:29:in `call'
  actionpack (4.1.1) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.1.1) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.1) lib/action_dispatch/routing/route_set.rb:676:in `call'
  rack-cors (0.2.9) lib/rack/cors.rb:54:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.1.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  activerecord (4.1.1) lib/active_record/migration.rb:380:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.1) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  better_errors (2.0.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.0.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.0.0) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.1) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.1) lib/action_dispatch/middleware/static.rb:64:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.1) lib/rails/engine.rb:514:in `call'
  railties (4.1.1) lib/rails/application.rb:144:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.3) lib/thin/connection.rb:53:in `process'
  thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.3) lib/eventmachine.rb:187:in `run'
  thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.3) lib/thin/server.rb:162:in `start'
  rack (1.5.2) lib/rack/handler/thin.rb:16:in `run'
  rack (1.5.2) lib/rack/server.rb:264:in `start'
  railties (4.1.1) lib/rails/commands/server.rb:69:in `start'
  railties (4.1.1) lib/rails/commands/commands_tasks.rb:81:in `block in server'
  railties (4.1.1) lib/rails/commands/commands_tasks.rb:76:in `server'
  railties (4.1.1) lib/rails/commands/commands_tasks.rb:40:in `run_command!'
  railties (4.1.1) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:8:in `<top (required)>'
  spring (1.1.3) lib/spring/client/rails.rb:27:in `call'
  spring (1.1.3) lib/spring/client/command.rb:7:in `call'
  spring (1.1.3) lib/spring/client.rb:26:in `run'
  spring (1.1.3) bin/spring:48:in `<top (required)>'
  spring (1.1.3) lib/spring/binstub.rb:11:in `<top (required)>'
  /Users/stephen/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  bin/spring:16:in `<top (required)>'
  bin/rails:3:in `<main>'
```

**Comment by faisal-ali** [comment]
It might sound stupid, but I was having the same issue, and all I did was swap [ gem 'grape' ] above [ gem 'grape-swagger' ] in Gemfile. It fixed the issue for me.

**Comment by dblock** [comment]
@faisal-ali That's actually quite interesting, we shouldn't be monkey patching Grape with anything and/or possibly failing if Grape is not defined yet. Can you open a new issue please and maybe build a small repro? Thanks.

**Comment by faisal-ali** [comment]
sure
