### ISSUE TITLE
Nested dynamic napespace problem (crash)

### ISSUE THREAD

**Issue by igneus** [ruby-grape/grape-swagger#267]
Let's have a `config.ru` defining a little API doing something with dates:

``` ruby
require 'grape'
require 'grape-swagger'

class API < Grape::API
  segment '/:year' do
    get do
      "Year #{params[:year]}"
    end

    segment '/:month' do
      get do
        "Month #{params[:year]}/#{params[:month]}"
      end

      get '/:day' do
        "Day #{params[:year]}-#{params[:month]}-#{params[:day]}"
      end
    end
  end

  add_swagger_documentation
end

run API
```

On startup `add_swagger_documentation` crashes:

```
/home/igneus/.rvm/gems/ruby-2.1.1/gems/grape-swagger-0.10.1/lib/grape-swagger.rb:70:in `block in combine_namespace_routes': undefined method `collect' for nil:NilClass (NoMethodError)
        from /home/igneus/.rvm/gems/ruby-2.1.1/gems/grape-swagger-0.10.1/lib/grape-swagger.rb:65:in `each'
        from /home/igneus/.rvm/gems/ruby-2.1.1/gems/grape-swagger-0.10.1/lib/grape-swagger.rb:65:in `combine_namespace_routes'
        from /home/igneus/.rvm/gems/ruby-2.1.1/gems/grape-swagger-0.10.1/lib/grape-swagger.rb:39:in `add_swagger_documentation'
        from /home/igneus/tmp/config.ru:21:in `<class:API>'
        from /home/igneus/tmp/config.ru:4:in `block in <main>'
        from /home/igneus/.rvm/gems/ruby-2.1.1/gems/rack-1.6.1/lib/rack/builder.rb:55:in `instance_eval'
        from /home/igneus/.rvm/gems/ruby-2.1.1/gems/rack-1.6.1/lib/rack/builder.rb:55:in `initialize'
        from /home/igneus/tmp/config.ru:in `new'
        from /home/igneus/tmp/config.ru:in `<main>'
        from /home/igneus/.rvm/gems/ruby-2.1.1/gems/rack-1.6.1/lib/rack/builder.rb:49:in `eval'
        from /home/igneus/.rvm/gems/ruby-2.1.1/gems/rack-1.6.1/lib/rack/builder.rb:49:in `new_from_string'
        from /home/igneus/.rvm/gems/ruby-2.1.1/gems/rack-1.6.1/lib/rack/builder.rb:40:in `parse_file'
        from /home/igneus/.rvm/gems/ruby-2.1.1/gems/rack-1.6.1/lib/rack/server.rb:299:in `build_app_and_options_from_config'
        from /home/igneus/.rvm/gems/ruby-2.1.1/gems/rack-1.6.1/lib/rack/server.rb:208:in `app'
        from /home/igneus/.rvm/gems/ruby-2.1.1/gems/rack-1.6.1/lib/rack/server.rb:336:in `wrapped_app'
        from /home/igneus/.rvm/gems/ruby-2.1.1/gems/rack-1.6.1/lib/rack/server.rb:272:in `start'
        from /home/igneus/.rvm/gems/ruby-2.1.1/gems/rack-1.6.1/lib/rack/server.rb:147:in `start'
        from /home/igneus/.rvm/gems/ruby-2.1.1/gems/rack-1.6.1/bin/rackup:4:in `<top (required)>'
        from /home/igneus/.rvm/gems/ruby-2.1.1/bin/rackup:23:in `load'
        from /home/igneus/.rvm/gems/ruby-2.1.1/bin/rackup:23:in `<main>'
        from /home/igneus/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
        from /home/igneus/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

Tested with
ruby 2.1.1
grape 0.11.0
grape-swagger 0.10.1 as well as current master

**Comment by xuyao91** [comment]
+1,I have the error too.

**Comment by galetahub** [comment]
+1
the same issue

**Comment by igneus** [comment]
I have been working on a fix, but I'm not sure if I will manage to complete it and make a pull request any soon.

**Comment by franzliedke** [comment]
I now encounter this error, too, although I'm doing something slightly different.

I have extracted all my endpoints into separate modules, like so:
~~~ruby
      namespace 'courses' do
        mount Endpoint::ListCourses

        params do
          requires :course_id, type: String, desc: 'The course UUID'
        end
        route_param :course_id do
          namespace 'learning_rooms' do
            mount Endpoint::CreateLearningRoom
          end

          namespace 'quizzes' do
            params do
              requires :quiz_id, type: String, desc: 'The quiz UUID'
            end
            route_param :quiz_id do
              mount Endpoint::ViewQuiz

              namespace 'submissions' do
                mount Endpoint::ViewQuizSubmissions
              end
            end
          end
        end
      end
~~~

This worked fine, until I started further nesting these classes, like so:
~~~ruby
Endpoint::Tables::ListTables
Endpoint::Tables::CreateTable
~~~

I don't know the code of this gem; can you point me to the root of this problem (the exception message doesn't say much) so that I can try to fix it?

**Comment by dblock** [comment]
A spec in this project would be helpful to start with.

**Comment by franzliedke** [comment]
For which issue exactly? The dynamic segments?

**Comment by dblock** [comment]
A minimal example that leads to this error.

**Comment by Satyricon** [comment]
No updates on this one?

**Comment by dblock** [comment]
I don't think anyone is actively working on a fix, please feel free to PR.

**Comment by thomaslitton** [comment]
I get a similar, but slightly different error with the latest release:

<pre>
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/grape-swagger-0.20.0/lib/grape-swagger.rb:87:in `block in combine_namespace_routes': undefined method `reject' for nil:NilClass (NoMethodError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/grape-swagger-0.20.0/lib/grape-swagger.rb:82:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/grape-swagger-0.20.0/lib/grape-swagger.rb:82:in `combine_namespace_routes'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/grape-swagger-0.20.0/lib/grape-swagger.rb:36:in `add_swagger_documentation'
</pre>

**Comment by Faisal-nfl** [comment]
I also facing kind of similar error
```
/home/faisal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-swagger-0.20.2/lib/grape-swagger.rb:66:in `combine_namespaces': undefined method `endpoints' for Kids:Module (NoMethodError)
	from /home/faisal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-swagger-0.20.2/lib/grape-swagger.rb:76:in `block in combine_namespaces'
	from /home/faisal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-swagger-0.20.2/lib/grape-swagger.rb:66:in `each'
	from /home/faisal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-swagger-0.20.2/lib/grape-swagger.rb:66:in `combine_namespaces'
	from /home/faisal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-swagger-0.20.2/lib/grape-swagger.rb:32:in `add_swagger_documentation'
	from /home/faisal/workspace/kidOrg/kidsapp-backend/app/api/api.rb:7:in `<class:API>'

```

**Comment by akwiatkowski** [comment]
I have also similar error. When I mount `Grape::API` class within namespace I get

```
/home/user/.rvm/gems/ruby-2.2.3@navigart/gems/grape-swagger-0.10.5/lib/grape-swagger.rb:26: The route_xxx methods such as route_path have been deprecated, please use path.
/home/user/.rvm/gems/ruby-2.2.3@navigart/gems/grape-swagger-0.10.5/lib/grape-swagger.rb:27: The route_xxx methods such as route_prefix have been deprecated, please use prefix.
/home/user/.rvm/gems/ruby-2.2.3@navigart/gems/grape-swagger-0.10.5/lib/grape-swagger.rb:34: The route_xxx methods such as route_path have been deprecated, please use path.
/home/user/.rvm/gems/ruby-2.2.3@navigart/gems/grape-swagger-0.10.5/lib/grape-swagger.rb:26: The route_xxx methods such as route_path have been deprecated, please use path.
/home/user/.rvm/gems/ruby-2.2.3@navigart/gems/grape-swagger-0.10.5/lib/grape-swagger.rb:27: The route_xxx methods such as route_prefix have been deprecated, please use prefix.
/home/user/.rvm/gems/ruby-2.2.3@navigart/gems/grape-swagger-0.10.5/lib/grape-swagger.rb:34: The route_xxx methods such as route_path have been deprecated, please use path.
/home/olek/.rvm/gems/ruby-2.2.3@navigart/gems/grape-swagger-0.10.5/lib/grape-swagger.rb:79:in `block in combine_namespace_routes': undefined method `collect' for nil:NilClass (NoMethodError)
```

**Comment by LeFnord** [comment]
think it can be closed 😉
