### ISSUE TITLE
parse_request_params failure

### ISSUE THREAD

**Issue by texpert** [ruby-grape/grape-swagger#366]
Hi!

I couldn't run at all swagger-2.0:
```
Started GET "/api/swagger_doc" for 89.28.12.13 at 2016-04-02 03:00:57 +0300
  
TypeError (no implicit conversion of Symbol into Integer):
  
/home/thunder/.rvm/gems/ruby-2.3.0/bundler/gems/grape-swagger-9a7e68753b32/lib/grape-swagger/endpoint.rb:209:in `[]'
/home/thunder/.rvm/gems/ruby-2.3.0/bundler/gems/grape-swagger-9a7e68753b32/lib/grape-swagger/endpoint.rb:209:in `block in parse_request_params'
/home/thunder/.rvm/gems/ruby-2.3.0/bundler/gems/grape-swagger-9a7e68753b32/lib/grape-swagger/endpoint.rb:208:in `each'
/home/thunder/.rvm/gems/ruby-2.3.0/bundler/gems/grape-swagger-9a7e68753b32/lib/grape-swagger/endpoint.rb:208:in `each_with_object'
/home/thunder/.rvm/gems/ruby-2.3.0/bundler/gems/grape-swagger-9a7e68753b32/lib/grape-swagger/endpoint.rb:208:in `parse_request_params'
/home/thunder/.rvm/gems/ruby-2.3.0/bundler/gems/grape-swagger-9a7e68753b32/lib/grape-swagger/endpoint.rb:190:in `partition_params'
```

Maybe the cause is this: have run debugger many times and didn't understand at all the line from partition_params:
```
required, exposed = route.route_params.partition { |x| x.first.is_a? String }
```
x.first being a String, IMHO, has absolutely no relevance to the parameter being required or exposed. I've  even given a try to a refactor, but it seems I have too little understanding of the grape and grape-swagger mechanics. (first, I have tried it with grape 0.15.0, but then read on the mailing list about 0.14.0 being only supported yet - but the result is the same).

**Comment by LeFnord** [comment]
please provide your API as a spec for reproducing and fixing …

and yeah … try refactoring

**Comment by texpert** [comment]
Sent to private mailbox.

**Comment by LeFnord** [comment]
tried it, and found something, see following:
```
desc 'Remove booking'
params do
  requires :id, type: Integer   # path parameter must be required
end
delete ':id' do                 # using of `:id` as path parameter
  { "declared_params" => declared(params) }
end
```

… if one specify a path parameter, this one must be required in the `params` block,
but besides, it should be raised a meaningful error message

change your code to this, should solve the error

**Comment by LeFnord** [comment]
setting path parameters to defaults (`{type: Integer, required: true}`) is done here: https://github.com/ruby-grape/grape-swagger/pull/367

**Comment by andrius** [comment]
Updated the gem and the code. Now there are no errors, but it won't work either - showing just:
```
fetching resource list: http://xxxxxx.ngrok.io/api/swagger_doc
```
...and that's all

**Comment by texpert** [comment]
Updated the gem and the code. Now there are no errors, but it won't work either - showing just:
```
fetching resource list: http://xxxxxx.ngrok.io/api/swagger_doc
```
...and that's all

**Comment by LeFnord** [comment]
mmh, you mean, you are running local server and want access the swagger via swagger-ui and grok, right?

did you have some output on the console?

maybe you can add a
```
rescue_from :all do |error|
  error_response(message: e.message, status: 500)
end
```
and pry in?

**Comment by texpert** [comment]
Yep, local server via swagger-ui and ngrok. There are no errors (I added rescue_from :all as you suggested). Gave a debugger run and also seen no errors - the response status was 200 and it passes further to Rack, then to Grape, Puma, etc....

The console's showing this:
```
foreman run bundle exec rails server -p 4001
DEPRECATION WARNING: Accessing mime types via constants is deprecated. Please change `Mime::JSON` to `Mime[:json]`. (called from const_missing at /home/thunder/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.beta3/lib/action_dispatch/http/mime_type.rb:52)
=> Booting Puma
=> Rails 5.0.0.beta3 application starting in development on http://localhost:4001
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[11991] Puma starting in cluster mode...
[11991] * Version 3.2.0 (ruby 2.3.0-p0), codename: Spring Is A Heliocentric Viewpoint
[11991] * Min threads: 5, max threads: 5
[11991] * Environment: development
[11991] * Process workers: 4
[11991] * Preloading application
[11991] * Listening on tcp://localhost:4001
[11991] Use Ctrl-C to stop
[11991] - Worker 0 (pid: 12001) booted, phase: 0
[11991] - Worker 1 (pid: 12015) booted, phase: 0
[11991] - Worker 2 (pid: 12029) booted, phase: 0
[11991] - Worker 3 (pid: 12038) booted, phase: 0
Started GET "/swagger" for 212.83.131.161 at 2016-04-04 17:04:49 +0300
  ActiveRecord::SchemaMigration Load (0.7ms)  SELECT "schema_migrations".* FROM "schema_migrations"
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from block (2 levels) in <module:ClassMethods> at /home/thunder/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.beta3/lib/abstract_controller/callbacks.rb:191)
Processing by GrapeSwaggerRails::ApplicationController#index as HTML
  Rendered /home/thunder/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0/gems/grape-swagger-rails-0.2.0/app/views/grape_swagger_rails/application/index.html.erb (208.8ms)
Completed 200 OK in 217ms (Views: 215.8ms | ActiveRecord: 0.0ms)


Started GET "/assets/grape_swagger_rails/application-74c486dc61c14dbfb81829f7b42a85b68066e0d7a4e5b1911c35989031e1e642.css" for 212.83.131.161 at 2016-04-04 17:04:50 +0300
Started GET "/assets/grape_swagger_rails/application-12746cd3432507ea6bbec712158c3f48dbaaaa1424e0bd6ae9d4c66025777437.js" for 212.83.131.161 at 2016-04-04 17:04:50 +0300
Started GET "/api/swagger_doc" for 212.83.131.161 at 2016-04-04 17:04:54 +0300
Started GET "/assets/grape_swagger_rails/logo_small-5d04ceb09bef69c924ccc23a35345a82211b77f44d0e16efabe87730ace0c6aa.png" for 212.83.131.161 at 2016-04-04 17:04:54 +0300
```

**Comment by LeFnord** [comment]
it seems that this is not a bug of grape-swagger, but to proof it, please could you create a spec to get the swagger … something like this:
```
require 'spec_helper'

RSpec.describe 'Endpoints', type: :request do
  include_context 'API v3 Authorization'

  subject do
    get "/v3/swagger_doc"
    JSON.parse(response.body)
  end

  specify { require 'pry'; binding.pry }
end
```

**Comment by texpert** [comment]
In such a spec, if adding add_swagger_documentation - everything's OK, if not - then error 404 'Not found' and some erro in JSON parsing:
```
[1] pry(#<RSpec::ExampleGroups::Endpoints>)> get "/swagger_doc"
=> #<Rack::MockResponse:0x0000000720eed0
 @block=nil,
 @body=["Not Found"],
 @body_string=nil,
 @errors="",
 @header={"Content-Type"=>"text/html", "X-Cascade"=>"pass", "Content-Length"=>"9"},
 @length=9,
 @original_headers={"Content-Type"=>"text/html", "X-Cascade"=>"pass"},
 @status=404,
 @writer=#<Proc:0x0000000720ed68@/home/thunder/.rvm/gems/ruby-2.3.0@global/gems/rack-2.0.0.alpha/lib/rack/response.rb:32 (lambda)>>
[2] pry(#<RSpec::ExampleGroups::Endpoints>)> JSON.parse(last_response.body)
JSON::ParserError: 784: unexpected token at 'Not Found'
from /home/thunder/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
```

**Comment by texpert** [comment]
But the weird thing is if I'm changing the single gem - 'grape-swagger' to master branch - then everything's working OK.

**Comment by LeFnord** [comment]
sorry, want you say without `add_swagger_documentation` you have an 404, right, and with it, is all fine?
if yes, this is expected, cause grape-swagger would be called with it …

**Comment by texpert** [comment]
All fine is, I mean, no errors, but, as I told earlier, no resources are displayed, just:
```
fetching resource list: http://xxxxxx.ngrok.io/api/swagger_doc
```

**Comment by LeFnord** [comment]
@dblock could you have an eye on … seems to be an `grape_swagger_rails` issue

**Comment by LeFnord** [comment]
@texpert one last idea … 
in your console output this route was called:
```
Started GET "/swagger" for 212.83.131.161 at 2016-04-04 17:04:49 +0300
```
could it be, that this one is wrong?

**Comment by texpert** [comment]
@LeFnord , the route is correct - it is working OK with the master branch of grape-swagger.
