### ISSUE TITLE
Broken on JRuby

### ISSUE THREAD

**Issue by dblock** [ruby-grape/grape-swagger#410]
https://travis-ci.org/ruby-grape/grape-swagger/jobs/128383239

```
NoMethodError:
        undefined method `bsearch' for #<Array:0xfb04727>
      # ./lib/grape-swagger/doc_methods/move_params.rb:78:in `nested_definitions'
      # ./lib/grape-swagger/doc_methods/move_params.rb:77:in `nested_definitions'
      # ./lib/grape-swagger/doc_methods/move_params.rb:52:in `move_params_to_new'
      # ./lib/grape-swagger/doc_methods/move_params.rb:42:in `find_definition_and_params'
      # ./lib/grape-swagger/doc_methods/move_params.rb:12:in `to_definition'
      # ./lib/grape-swagger/doc_methods/move_params.rb:19:in `find_post_put'
      # ./lib/grape-swagger/doc_methods/move_params.rb:17:in `find_post_put'
      # ./lib/grape-swagger/doc_methods/move_params.rb:8:in `to_definition'
      # ./lib/grape-swagger/endpoint.rb:74:in `path_and_definition_objects'
```

**Comment by LeFnord** [comment]
Yeap, that is correct behavior for older jrubies, try with jruby-9.0.5.x and re-add it to the Travis file

**Comment by LeFnord** [comment]
resolved here https://github.com/ruby-grape/grape-swagger/pull/422
