### ISSUE TITLE
Ruby 2.3 - frozen string literal compatibility issues

### ISSUE THREAD

**Issue by mattyr** [ruby-grape/grape-swagger#590]
i originally mentioned in pr #589 , but there are rubocop failures if you run ```bundle exec rake``` under ruby 2.3.

the source of the issue is rubocop's [FrozenStringLiteralComment](http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/FrozenStringLiteralComment) check, which fails if missing the comment in source code files (which is the case for a lot of the files in the project).

the issue is that globally adding those comments introduces bugs, ie:

```
1) GrapeSwagger::DocMethods::OperationId build :get 
     Failure/Error: let(:route) { Grape::Router::Route.new(method, '/path', requirements: {}) }
     
     RuntimeError:
       can't modify frozen String
     # /Users/matt/.rvm/gems/ruby-2.3.3@grape-swagger/gems/grape-0.19.1/lib/grape/router/pattern.rb:39:in `build_path'
     # /Users/matt/.rvm/gems/ruby-2.3.3@grape-swagger/gems/grape-0.19.1/lib/grape/router/pattern.rb:19:in `initialize'
     # /Users/matt/.rvm/gems/ruby-2.3.3@grape-swagger/gems/grape-0.19.1/lib/grape/router/route.rb:67:in `new'
     # /Users/matt/.rvm/gems/ruby-2.3.3@grape-swagger/gems/grape-0.19.1/lib/grape/router/route.rb:67:in `initialize'
     # ./spec/lib/operation_id_spec.rb:11:in `new'
     # ./spec/lib/operation_id_spec.rb:11:in `block (3 levels) in <top (required)>'
     # ./spec/lib/operation_id_spec.rb:23:in `block (4 levels) in <top (required)>'
```

the source of the issue isn't always grape-swagger, but as in the example above, grape itself

seems to me there are a few directions to go to "fix" this:

- make the referenced gems, and grape-swagger, compatible with frozen strings
- globally ignore the FrozenStringLiteralComment in rubocop.yml
- selectively include the frozen string literal comment in grape-swagger's files, and add specific ignores in rubocop.yml
- don't support ruby >= 2.3

not a fan of the last option, seems like the first option is best but might take some coordination.

(btw -- the only errors were generated from spec/lib/operation_id_spec.rb, but i'm not sure if that's the tip of an iceberg).

thoughts?

**Comment by mattyr** [comment]
Just a note - you can have rubocop insert the missing comments and replicate the errors (assuming you are using ruby >= 2.3):

```sh
bundle exec rubocop --auto-correct --only FrozenStringLiteralComment
bundle exec rake
```

**Comment by LeFnord** [comment]
actually it was only added, where it was needed – only in two files :(.
So I tried to reproduce it, switched the ruby version, bundled it, run rake …

<img width="912" alt="ruby2 3 0" src="https://cloud.githubusercontent.com/assets/120214/23475014/44cbe4fe-feb6-11e6-86da-45529cab838d.png">

<img width="792" alt="ruby 2 4 0" src="https://cloud.githubusercontent.com/assets/120214/23475018/48b7a760-feb6-11e6-8219-9c996678533b.png">

**Comment by mattyr** [comment]
Very strange... here's what I'm getting.  Maybe it's a rubocop version or something?  Do you have any additional .rubocop.yml files?

```sh
➜  grape-swagger git:(upstream) bundle exec rake
/Users/matt/.rvm/rubies/ruby-2.3.3/bin/ruby -I/Users/matt/.rvm/gems/ruby-2.3.3@grape-swagger/gems/rspec-core-3.5.4/lib:/Users/matt/.rvm/gems/ruby-2.3.3@grape-swagger/gems/rspec-support-3.5.0/lib /Users/matt/.rvm/gems/ruby-2.3.3@grape-swagger/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.

Randomized with seed 40834
......................................................................................................[GrapeSwagger] usage of foo is deprecated
.................................................................................................................................................................................................................................................

Finished in 2.11 seconds (files took 0.65793 seconds to load)
343 examples, 0 failures

Randomized with seed 40834

[Coveralls] Outside the CI environment, not sending data.
Running RuboCop...
Inspecting 106 files
CCCCCCCCCCCCCCC.CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC.CCCCCCCCCCCCCCCCCCCC

Offenses:

Gemfile:1:1: C: Missing frozen string literal comment.
source 'http://rubygems.org'
^
grape-swagger.gemspec:1:1: C: Missing frozen string literal comment.
$LOAD_PATH.push File.expand_path('../lib', __FILE__)
^
Rakefile:1:1: C: Missing frozen string literal comment.
# encoding: utf-8
^
lib/grape-swagger/doc_methods/build_model_definition.rb:1:1: C: Missing frozen string literal comment.
module GrapeSwagger
^
lib/grape-swagger/doc_methods/data_type.rb:1:1: C: Missing frozen string literal comment.
module GrapeSwagger
^
lib/grape-swagger/doc_methods/extensions.rb:1:1: C: Missing frozen string literal comment.
module GrapeSwagger
^
lib/grape-swagger/doc_methods/headers.rb:1:1: C: Missing frozen string literal comment.
module GrapeSwagger
^
lib/grape-swagger/doc_methods/move_params.rb:1:1: C: Missing frozen string literal comment.
module GrapeSwagger
^
lib/grape-swagger/doc_methods/operation_id.rb:1:1: C: Missing frozen string literal comment.
module GrapeSwagger
^
lib/grape-swagger/doc_methods/optional_object.rb:1:1: C: Missing frozen string literal comment.
module GrapeSwagger
^
lib/grape-swagger/doc_methods/parse_params.rb:1:1: C: Missing frozen string literal comment.
module GrapeSwagger
^
lib/grape-swagger/doc_methods/path_string.rb:1:1: C: Missing frozen string literal comment.
module GrapeSwagger
^
lib/grape-swagger/doc_methods/produces_consumes.rb:1:1: C: Missing frozen string literal comment.
module GrapeSwagger
^
lib/grape-swagger/doc_methods/status_codes.rb:1:1: C: Missing frozen string literal comment.
module GrapeSwagger
^
lib/grape-swagger/doc_methods/tag_name_description.rb:1:1: C: Missing frozen string literal comment.
module GrapeSwagger
^
lib/grape-swagger/doc_methods.rb:1:1: C: Missing frozen string literal comment.
require 'grape-swagger/doc_methods/status_codes'
^
lib/grape-swagger/endpoint.rb:1:1: C: Missing frozen string literal comment.
require 'active_support'
^
lib/grape-swagger/errors.rb:1:1: C: Missing frozen string literal comment.
module GrapeSwagger
^
lib/grape-swagger/model_parsers.rb:1:1: C: Missing frozen string literal comment.
module GrapeSwagger
^
lib/grape-swagger/rake/oapi_tasks.rb:1:1: C: Missing frozen string literal comment.
require 'rake'
^
lib/grape-swagger/version.rb:1:1: C: Missing frozen string literal comment.
module GrapeSwagger
^
lib/grape-swagger.rb:1:1: C: Missing frozen string literal comment.
require 'grape'
^
spec/issues/403_versions_spec.rb:1:1: C: Missing frozen string literal comment.
# encoding: utf-8
^
spec/issues/427_entity_as_string_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/issues/430_entity_definitions_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/issues/532_allow_custom_format_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/issues/533_specify_status_code_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/issues/537_enum_values_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/issues/539_array_post_body_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/issues/542_array_of_type_in_post_body_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/issues/553_align_array_put_post_params_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/issues/572_array_post_body_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/issues/579_align_put_post_parameters_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/issues/582_file_response_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/issues/587_range_parameter_delimited_by_dash_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/lib/data_type_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/lib/endpoint_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/lib/extensions_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/lib/model_parsers_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/lib/move_params_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/lib/oapi_tasks_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/lib/operation_id_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/lib/optional_object_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/lib/parse_params_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/lib/path_string_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/lib/produces_consumes_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/lib/tag_name_description_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/lib/version_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/spec_helper.rb:1:1: C: Missing frozen string literal comment.
require 'simplecov'
^
spec/support/empty_model_parser.rb:1:1: C: Missing frozen string literal comment.
class EmptyClass
^
spec/support/grape_version.rb:1:1: C: Missing frozen string literal comment.
class GrapeVersion
^
spec/support/mock_parser.rb:1:1: C: Missing frozen string literal comment.
module GrapeSwagger
^
spec/support/model_parsers/entity_parser.rb:1:1: C: Missing frozen string literal comment.
RSpec.shared_context 'entity swagger example' do
^
spec/support/model_parsers/mock_parser.rb:1:1: C: Missing frozen string literal comment.
RSpec.shared_context 'mock swagger example' do
^
spec/support/model_parsers/representable_parser.rb:1:1: C: Missing frozen string literal comment.
require 'representable/json'
^
spec/support/namespace_tags.rb:1:1: C: Missing frozen string literal comment.
RSpec.shared_context 'namespace example' do
^
spec/support/the_paths_definitions.rb:1:1: C: Missing frozen string literal comment.
RSpec.shared_context 'the api paths/defs' do
^
spec/swagger_v2/api_swagger_v2_body_definitions_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/api_swagger_v2_definitions-models_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/api_swagger_v2_detail_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/api_swagger_v2_extensions_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/api_swagger_v2_format-content_type_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/api_swagger_v2_global_configuration_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/api_swagger_v2_hash_and_array_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/api_swagger_v2_headers_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/api_swagger_v2_hide_documentation_path_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/api_swagger_v2_hide_param_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/api_swagger_v2_ignore_defaults_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/api_swagger_v2_mounted_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/api_swagger_v2_param_type_body_nested_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/api_swagger_v2_param_type_body_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/api_swagger_v2_param_type_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/api_swagger_v2_request_params_fix_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/api_swagger_v2_response_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/api_swagger_v2_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/api_swagger_v2_type-format_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/boolean_params_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/default_api_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/description_not_initialized.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/endpoint_versioned_path_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/errors_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/float_api_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/form_params_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/grape-swagger_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/hide_api_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/host.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/mounted_target_class_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/namespace_tags_prefix_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/namespace_tags_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/namespaced_api_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/nicknamed_api_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/operation_id_api_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/param_multi_type_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/param_type_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/param_values_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/params_array_collection_fromat_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/params_array_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/params_hash_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/params_nested_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/parent_less_namespace.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/reference_entity.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/security_requirement_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/swagger_v2/simple_mounted_api_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^
spec/version_spec.rb:1:1: C: Missing frozen string literal comment.
require 'spec_helper'
^

106 files inspected, 104 offenses detected
RuboCop failed!
➜  grape-swagger git:(upstream) ruby --version
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
➜  grape-swagger git:(upstream) bundle show
Gems included by the bundle:
  * activesupport (5.0.1)
  * addressable (2.5.0)
  * ast (2.3.0)
  * axiom-types (0.1.1)
  * builder (3.2.3)
  * bundler (1.14.5)
  * byebug (9.0.6)
  * claide (1.0.1)
  * claide-plugins (0.9.2)
  * coderay (1.1.1)
  * coercible (1.0.0)
  * colored (1.2)
  * concurrent-ruby (1.0.5)
  * cork (0.2.0)
  * coveralls (0.8.19)
  * danger (4.0.5)
  * danger-changelog (0.2.1)
  * danger-plugin-api (1.0.0)
  * descendants_tracker (0.0.4)
  * diff-lcs (1.3)
  * docile (1.1.5)
  * equalizer (0.0.11)
  * faraday (0.11.0)
  * faraday-http-cache (1.3.1)
  * git (1.3.0)
  * grape (0.19.1)
  * grape-entity (0.6.1)
  * grape-swagger (0.26.1)
  * grape-swagger-entity (0.1.6)
  * hashie (3.5.5)
  * i18n (0.8.1)
  * ice_nine (0.11.2)
  * json (2.0.3)
  * kramdown (1.13.2)
  * method_source (0.8.2)
  * minitest (5.10.1)
  * multi_json (1.12.1)
  * multi_xml (0.6.0)
  * multipart-post (2.0.0)
  * mustermann (0.4.0)
  * mustermann-grape (0.4.0)
  * nap (1.1.0)
  * octokit (4.6.2)
  * open4 (1.3.4)
  * parser (2.4.0.0)
  * powerpack (0.1.1)
  * pry (0.10.4)
  * pry-byebug (3.4.2)
  * public_suffix (2.0.5)
  * rack (2.0.1)
  * rack-accept (0.4.5)
  * rack-cors (0.4.1)
  * rack-test (0.6.3)
  * rainbow (2.2.1)
  * rake (12.0.0)
  * rdoc (5.1.0)
  * rspec (3.5.0)
  * rspec-core (3.5.4)
  * rspec-expectations (3.5.0)
  * rspec-mocks (3.5.0)
  * rspec-support (3.5.0)
  * rubocop (0.47.1)
  * ruby-grape-danger (0.1.1)
  * ruby-progressbar (1.8.1)
  * sawyer (0.8.1)
  * simplecov (0.12.0)
  * simplecov-html (0.10.0)
  * slop (3.6.0)
  * term-ansicolor (1.4.0)
  * terminal-table (1.7.3)
  * thor (0.19.4)
  * thread_safe (0.3.6)
  * tins (1.13.2)
  * tool (0.2.3)
  * tzinfo (1.2.2)
  * unicode-display_width (1.1.3)
  * virtus (1.0.5)
```

**Comment by LeFnord** [comment]
yeap … that is it, I see no difference, besides ruby 2.3.0 vs 2.3.3 and rbenv vs rvm,
but both of them should not be the reason for the different behavior …
but without reproducing it, a fixing of it is difficult 😉

besides that, travis was green on your PRs, there are also ruby 2.3.3 and 2.4.0 running, check the details on it …

… any idea?

**Comment by mattyr** [comment]
sooooo, i think it might be related to this:

https://github.com/bbatsov/rubocop/issues/3284
and at root this:
https://github.com/bbatsov/rubocop/issues/2956

if you add a .ruby-version with "2.3.3" as content in your project folder, then rubocop, do you get the errors?  if so, then I think that the testing (and travis) setup might have a bug in them -- rubocop might not be using the appropriate parser for the ruby version running.

... could be way off base here though.

**Comment by LeFnord** [comment]
hi @mattyr … also with 2.3.3 nothings :(
<img width="682" alt="bildschirmfoto 2017-03-07 um 17 23 49" src="https://cloud.githubusercontent.com/assets/120214/23666285/dfa9734e-035a-11e7-8fbc-43cbe1d638e5.png">

… but feel free to fix it – can't do it, cause nothings happen – would prefer to ignore `Rakefile`, `Gemfile` and `grape-swagger.gemspec` and only adapt the other files.

**Comment by mattyr** [comment]
can you try this in your working dir:

```sh
echo 2.3.3 >> .ruby-version
bundle exec rake
```

i think it's the ".ruby-version" file itself, not the version of ruby (from the above referenced issues for rubocop).

... looking to confirm that it is indeed something unique to your setup that is causing those tests to be skipped, rather than something strange about mine.  there then comes the issue of where it's appropriate to fix (grape itself has some issues with frozen strings), etc -- so best to confirm where we sit first, right?

**Comment by LeFnord** [comment]
as I said, I can not re-produce it, using `rbenv` creates this file, see above screenshot

**Comment by mattyr** [comment]
right, totally got that -- do you have .ruby-version file at all in the directory?  If you see the issues I link to above, the existence of that file can actually affect which tests are run in rubocop.  IOW -- you can have different behaviors, if:

- You do not have a .ruby-version file
- You have 2.3.3 in the .ruby-version file (it then checks for frozen string literals)
- You have < 2.3 in the .ruby-version file (it then does *not* check for frozen string literals)

**Comment by LeFnord** [comment]
think it has nothings to do with it …
but can re-produce it by setting the `TargetRubyVersion` in the rubucop.yml

**Comment by LeFnord** [comment]
#595 should solve it

**Comment by mattyr** [comment]
so #595 addresses part of it, but i think you may introduce breaking bugs -- does the test suite pass for you with all of those frozen string literals in place?

the TargetRubyVersion is tied with the .ruby-version -- just to close the loop, can you share the output of this command:

```sh
cat .ruby-version
```

i feel like we're circling around the same issue but are maybe missing ever so slightly...?

**Comment by LeFnord** [comment]
heap, the suite passes, see the travis checks on the PR

**Comment by mattyr** [comment]
ok, cool.  well at least rubocop runs cleanly now on my machine... thanks!
