### ISSUE TITLE
uninitialized class variable @@hide_format

### ISSUE THREAD

**Issue by Jokery** [ruby-grape/grape-swagger#60]
NameError (uninitialized class variable @@hide_format in #Class:0x00000006debf88):
  grape-swagger (0.6.0) lib/grape-swagger.rb:68:in `block (2 levels) in setup'

i'm using mruby 1.9.2-p290, i dont know whether this will work on higher version, but simply i dont think initialize a class variable in Class.new(Grape::API) can be reached in helpers do(which means Module.new)

**Comment by tian-xiaobo** [comment]
I can see again this issue. I get:

```

Started GET "/api/v1/swagger_doc" for 127.0.0.1 at 2015-01-21 10:54:58 +0800

NameError (uninitialized class variable @@hide_format in #<Module:0x007ff377514240>):
  /use/36kr/bundle/ruby/2.2.0/gems/grape-swagger-0.7.2/lib/grape-swagger.rb:269:in `parse_path'
  /use/36kr/bundle/ruby/2.2.0/gems/grape-swagger-0.7.2/lib/grape-swagger.rb:90:in `block (2 levels) in setup'
  /use/36kr/bundle/ruby/2.2.0/gems/grape-swagger-0.7.2/lib/grape-swagger.rb:90:in `reject!'
  /use/36kr/bundle/ruby/2.2.0/gems/grape-swagger-0.7.2/lib/grape-swagger.rb:90:in `block in setup'
  /use/36kr/bundle/ruby/2.2.0/gems/grape-0.10.1/lib/grape/endpoint.rb:47:in `call'
  /use/36kr/bundle/ruby/2.2.0/gems/grape-0.10.1/lib/grape/endpoint.rb:47:in `block in generate_api_method'
  /use/36kr/bundle/ruby/2.2.0/gems/grape-0.10.1/lib/grape/endpoint.rb:247:in `call'
  /use/36kr/bundle/ruby/2.2.0/gems/grape-0.10.1/lib/grape/endpoint.rb:247:in `run'
  /use/36kr/bundle/ruby/2.2.0/gems/grape-0.10.1/lib/grape/endpoint.rb:195:in `block in call!'
  /use/36kr/bundle/ruby/2.2.0/gems/grape-0.10.1/lib/grape/middleware/base.rb:24:in `call'
  /use/36kr/bundle/ruby/2.2.0/gems/grape-0.10.1/lib/grape/middleware/base.rb:24:in `call!'
  /use/36kr/bundle/ruby/2.2.0/gems/grape-0.10.1/lib/grape/middleware/base.rb:18:in `call'
  /use/36kr/bundle/ruby/2.2.0/gems/grape-0.10.1/lib/grape/middleware/base.rb:24:in `call!'
  /use/36kr/bundle/ruby/2.2.0/gems/grape-0.10.1/lib/grape/middleware/base.rb:18:in `call'
  /use/36kr/bundle/ruby/2.2.0/gems/grape-0.10.1/lib/grape/middleware/error.rb:27:in `block in call!'
  /use/36kr/bundle/ruby/2.2.0/gems/grape-0.10.1/lib/grape/middleware/error.rb:26:in `catch'
  /use/36kr/bundle/ruby/2.2.0/gems/grape-0.10.1/lib/grape/middleware/error.rb:26:in `call!'
  /use/36kr/bundle/ruby/2.2.0/gems/grape-0.10.1/lib/grape/middleware/base.rb:18:in `call'
```

**Comment by tian-xiaobo** [comment]
what  fixed on HEAD where code?

**Comment by dblock** [comment]
@tian-xiaobo You're using grape-swagger 0.7.2, which doesn't support grape 0.10.1, upgrade to the latest, 0.9.0.
